type token_kind =
  | KW_ALIGNOF
  | KW_ASM
  | KW_ATTRIBUTE
  | KW_AUTO
  | KW_BREAK
  | KW_CASE
  | KW_CHAR
  | KW_COMPLEX
  | KW_CONST
  | KW_CONTINUE
  | KW_DEFAULT
  | KW_DO
  | KW_DOUBLE
  | KW_ELSE
  | KW_ENUM
  | KW_EXTENSION
  | KW_EXTERN
  | KW_FLOAT
  | KW_FOR
  | KW_GOTO
  | KW_IF
  | KW_IMAG
  | KW_INLINE
  | KW_INT
  | KW_LONG
  | KW_REAL
  | KW_REGISTER
  | KW_RESTRICT
  | KW_RETURN
  | KW_SHORT
  | KW_SIGNED
  | KW_SIZEOF
  | KW_STATIC
  | KW_STRUCT
  | KW_SWITCH
  | KW_TYPEDEF
  | KW_TYPEOF
  | KW_UNION
  | KW_UNSIGNED
  | KW_VA_ARG
  | KW_VA_LIST
  | KW_VOID
  | KW_VOLATILE
  | KW_WCHAR_T
  | KW_WHILE
  | TK_AND
  | TK_ANDAND
  | TK_AND_EQ
  | TK_ARROW
  | TK_CARET
  | TK_CARET_EQ
  | TK_CHAR_CONSTANT
  | TK_COLON
  | TK_COMMA
  | TK_COMMENT
  | TK_DEC
  | TK_ELLIPSIS
  | TK_EOF
  | TK_EQEQ
  | TK_EQUALS
  | TK_ERROR
  | TK_EXMARK
  | TK_FLOATING_CONSTANT
  | TK_GREATER
  | TK_GREATER_EQ
  | TK_GTGT
  | TK_GTGT_EQ
  | TK_HASH
  | TK_HASHHASH
  | TK_HEX_CONSTANT
  | TK_IDENTIFIER
  | TK_INC
  | TK_INCLUDE
  | TK_INTEGER_CONSTANT
  | TK_LBRACE
  | TK_LBRACK
  | TK_LESS
  | TK_LESS_EQ
  | TK_LSQBRACK
  | TK_LTLT
  | TK_LTLT_EQ
  | TK_MINUS
  | TK_MINUS_EQ
  | TK_NE
  | TK_OCTAL_CONSTANT
  | TK_PERCENT
  | TK_PERCENT_EQ
  | TK_PERIOD
  | TK_PIPE
  | TK_PIPE_EQ
  | TK_PIPEPIPE
  | TK_PLUS
  | TK_PLUS_EQ
  | TK_QMARK
  | TK_RBRACE
  | TK_RBRACK
  | TK_RSQBRACK
  | TK_SEMICOLON
  | TK_SLASH
  | TK_SLASH_EQ
  | TK_STAR
  | TK_STAR_EQ
  | TK_STRING_LITERAL
  | TK_TILDE
  | TK_TYPEDEF_NAME
  | TK_WCHAR_CONSTANT
  | TK_WSTRING_LITERAL
;;

let token_kind_of_string s =
  match s with
  | "KW_ALIGNOF" -> KW_ALIGNOF
  | "KW_ASM" -> KW_ASM
  | "KW_ATTRIBUTE" -> KW_ATTRIBUTE
  | "KW_AUTO" -> KW_AUTO
  | "KW_BREAK" -> KW_BREAK
  | "KW_CASE" -> KW_CASE
  | "KW_CHAR" -> KW_CHAR
  | "KW_COMPLEX" -> KW_COMPLEX
  | "KW_CONST" -> KW_CONST
  | "KW_CONTINUE" -> KW_CONTINUE
  | "KW_DEFAULT" -> KW_DEFAULT
  | "KW_DO" -> KW_DO
  | "KW_DOUBLE" -> KW_DOUBLE
  | "KW_ELSE" -> KW_ELSE
  | "KW_ENUM" -> KW_ENUM
  | "KW_EXTENSION" -> KW_EXTENSION
  | "KW_EXTERN" -> KW_EXTERN
  | "KW_FLOAT" -> KW_FLOAT
  | "KW_FOR" -> KW_FOR
  | "KW_GOTO" -> KW_GOTO
  | "KW_IF" -> KW_IF
  | "KW_IMAG" -> KW_IMAG
  | "KW_INLINE" -> KW_INLINE
  | "KW_INT" -> KW_INT
  | "KW_LONG" -> KW_LONG
  | "KW_REAL" -> KW_REAL
  | "KW_REGISTER" -> KW_REGISTER
  | "KW_RESTRICT" -> KW_RESTRICT
  | "KW_RETURN" -> KW_RETURN
  | "KW_SHORT" -> KW_SHORT
  | "KW_SIGNED" -> KW_SIGNED
  | "KW_SIZEOF" -> KW_SIZEOF
  | "KW_STATIC" -> KW_STATIC
  | "KW_STRUCT" -> KW_STRUCT
  | "KW_SWITCH" -> KW_SWITCH
  | "KW_TYPEDEF" -> KW_TYPEDEF
  | "KW_TYPEOF" -> KW_TYPEOF
  | "KW_UNION" -> KW_UNION
  | "KW_UNSIGNED" -> KW_UNSIGNED
  | "KW_VA_ARG" -> KW_VA_ARG
  | "KW_VA_LIST" -> KW_VA_LIST
  | "KW_VOID" -> KW_VOID
  | "KW_VOLATILE" -> KW_VOLATILE
  | "KW_WCHAR_T" -> KW_WCHAR_T
  | "KW_WHILE" -> KW_WHILE
  | "TK_AND" -> TK_AND
  | "TK_ANDAND" -> TK_ANDAND
  | "TK_AND_EQ" -> TK_AND_EQ
  | "TK_ARROW" -> TK_ARROW
  | "TK_CARET" -> TK_CARET
  | "TK_CARET_EQ" -> TK_CARET_EQ
  | "TK_CHAR_CONSTANT" -> TK_CHAR_CONSTANT
  | "TK_COLON" -> TK_COLON
  | "TK_COMMA" -> TK_COMMA
  | "TK_COMMENT" -> TK_COMMENT
  | "TK_DEC" -> TK_DEC
  | "TK_ELLIPSIS" -> TK_ELLIPSIS
  | "TK_EOF" -> TK_EOF
  | "TK_EQEQ" -> TK_EQEQ
  | "TK_EQUALS" -> TK_EQUALS
  | "TK_ERROR" -> TK_ERROR
  | "TK_EXMARK" -> TK_EXMARK
  | "TK_FLOATING_CONSTANT" -> TK_FLOATING_CONSTANT
  | "TK_GREATER" -> TK_GREATER
  | "TK_GREATER_EQ" -> TK_GREATER_EQ
  | "TK_GTGT" -> TK_GTGT
  | "TK_GTGT_EQ" -> TK_GTGT_EQ
  | "TK_HASH" -> TK_HASH
  | "TK_HASHHASH" -> TK_HASHHASH
  | "TK_HEX_CONSTANT" -> TK_HEX_CONSTANT
  | "TK_IDENTIFIER" -> TK_IDENTIFIER
  | "TK_INC" -> TK_INC
  | "TK_INCLUDE" -> TK_INCLUDE
  | "TK_INTEGER_CONSTANT" -> TK_INTEGER_CONSTANT
  | "TK_LBRACE" -> TK_LBRACE
  | "TK_LBRACK" -> TK_LBRACK
  | "TK_LESS" -> TK_LESS
  | "TK_LESS_EQ" -> TK_LESS_EQ
  | "TK_LSQBRACK" -> TK_LSQBRACK
  | "TK_LTLT" -> TK_LTLT
  | "TK_LTLT_EQ" -> TK_LTLT_EQ
  | "TK_MINUS" -> TK_MINUS
  | "TK_MINUS_EQ" -> TK_MINUS_EQ
  | "TK_NE" -> TK_NE
  | "TK_OCTAL_CONSTANT" -> TK_OCTAL_CONSTANT
  | "TK_PERCENT" -> TK_PERCENT
  | "TK_PERCENT_EQ" -> TK_PERCENT_EQ
  | "TK_PERIOD" -> TK_PERIOD
  | "TK_PIPE" -> TK_PIPE
  | "TK_PIPE_EQ" -> TK_PIPE_EQ
  | "TK_PIPEPIPE" -> TK_PIPEPIPE
  | "TK_PLUS" -> TK_PLUS
  | "TK_PLUS_EQ" -> TK_PLUS_EQ
  | "TK_QMARK" -> TK_QMARK
  | "TK_RBRACE" -> TK_RBRACE
  | "TK_RBRACK" -> TK_RBRACK
  | "TK_RSQBRACK" -> TK_RSQBRACK
  | "TK_SEMICOLON" -> TK_SEMICOLON
  | "TK_SLASH" -> TK_SLASH
  | "TK_SLASH_EQ" -> TK_SLASH_EQ
  | "TK_STAR" -> TK_STAR
  | "TK_STAR_EQ" -> TK_STAR_EQ
  | "TK_STRING_LITERAL" -> TK_STRING_LITERAL
  | "TK_TILDE" -> TK_TILDE
  | "TK_TYPEDEF_NAME" -> TK_TYPEDEF_NAME
  | "TK_WCHAR_CONSTANT" -> TK_WCHAR_CONSTANT
  | "TK_WSTRING_LITERAL" -> TK_WSTRING_LITERAL
;;

let string_of_token_kind s =
  match s with
  | KW_ALIGNOF -> "KW_ALIGNOF"
  | KW_ASM -> "KW_ASM"
  | KW_ATTRIBUTE -> "KW_ATTRIBUTE"
  | KW_AUTO -> "KW_AUTO"
  | KW_BREAK -> "KW_BREAK"
  | KW_CASE -> "KW_CASE"
  | KW_CHAR -> "KW_CHAR"
  | KW_COMPLEX -> "KW_COMPLEX"
  | KW_CONST -> "KW_CONST"
  | KW_CONTINUE -> "KW_CONTINUE"
  | KW_DEFAULT -> "KW_DEFAULT"
  | KW_DO -> "KW_DO"
  | KW_DOUBLE -> "KW_DOUBLE"
  | KW_ELSE -> "KW_ELSE"
  | KW_ENUM -> "KW_ENUM"
  | KW_EXTENSION -> "KW_EXTENSION"
  | KW_EXTERN -> "KW_EXTERN"
  | KW_FLOAT -> "KW_FLOAT"
  | KW_FOR -> "KW_FOR"
  | KW_GOTO -> "KW_GOTO"
  | KW_IF -> "KW_IF"
  | KW_IMAG -> "KW_IMAG"
  | KW_INLINE -> "KW_INLINE"
  | KW_INT -> "KW_INT"
  | KW_LONG -> "KW_LONG"
  | KW_REAL -> "KW_REAL"
  | KW_REGISTER -> "KW_REGISTER"
  | KW_RESTRICT -> "KW_RESTRICT"
  | KW_RETURN -> "KW_RETURN"
  | KW_SHORT -> "KW_SHORT"
  | KW_SIGNED -> "KW_SIGNED"
  | KW_SIZEOF -> "KW_SIZEOF"
  | KW_STATIC -> "KW_STATIC"
  | KW_STRUCT -> "KW_STRUCT"
  | KW_SWITCH -> "KW_SWITCH"
  | KW_TYPEDEF -> "KW_TYPEDEF"
  | KW_TYPEOF -> "KW_TYPEOF"
  | KW_UNION -> "KW_UNION"
  | KW_UNSIGNED -> "KW_UNSIGNED"
  | KW_VA_ARG -> "KW_VA_ARG"
  | KW_VA_LIST -> "KW_VA_LIST"
  | KW_VOID -> "KW_VOID"
  | KW_VOLATILE -> "KW_VOLATILE"
  | KW_WCHAR_T -> "KW_WCHAR_T"
  | KW_WHILE -> "KW_WHILE"
  | TK_AND -> "TK_AND"
  | TK_ANDAND -> "TK_ANDAND"
  | TK_AND_EQ -> "TK_AND_EQ"
  | TK_ARROW -> "TK_ARROW"
  | TK_CARET -> "TK_CARET"
  | TK_CARET_EQ -> "TK_CARET_EQ"
  | TK_CHAR_CONSTANT -> "TK_CHAR_CONSTANT"
  | TK_COLON -> "TK_COLON"
  | TK_COMMA -> "TK_COMMA"
  | TK_COMMENT -> "TK_COMMENT"
  | TK_DEC -> "TK_DEC"
  | TK_ELLIPSIS -> "TK_ELLIPSIS"
  | TK_EOF -> "TK_EOF"
  | TK_EQEQ -> "TK_EQEQ"
  | TK_EQUALS -> "TK_EQUALS"
  | TK_ERROR -> "TK_ERROR"
  | TK_EXMARK -> "TK_EXMARK"
  | TK_FLOATING_CONSTANT -> "TK_FLOATING_CONSTANT"
  | TK_GREATER -> "TK_GREATER"
  | TK_GREATER_EQ -> "TK_GREATER_EQ"
  | TK_GTGT -> "TK_GTGT"
  | TK_GTGT_EQ -> "TK_GTGT_EQ"
  | TK_HASH -> "TK_HASH"
  | TK_HASHHASH -> "TK_HASHHASH"
  | TK_HEX_CONSTANT -> "TK_HEX_CONSTANT"
  | TK_IDENTIFIER -> "TK_IDENTIFIER"
  | TK_INC -> "TK_INC"
  | TK_INCLUDE -> "TK_INCLUDE"
  | TK_INTEGER_CONSTANT -> "TK_INTEGER_CONSTANT"
  | TK_LBRACE -> "TK_LBRACE"
  | TK_LBRACK -> "TK_LBRACK"
  | TK_LESS -> "TK_LESS"
  | TK_LESS_EQ -> "TK_LESS_EQ"
  | TK_LSQBRACK -> "TK_LSQBRACK"
  | TK_LTLT -> "TK_LTLT"
  | TK_LTLT_EQ -> "TK_LTLT_EQ"
  | TK_MINUS -> "TK_MINUS"
  | TK_MINUS_EQ -> "TK_MINUS_EQ"
  | TK_NE -> "TK_NE"
  | TK_OCTAL_CONSTANT -> "TK_OCTAL_CONSTANT"
  | TK_PERCENT -> "TK_PERCENT"
  | TK_PERCENT_EQ -> "TK_PERCENT_EQ"
  | TK_PERIOD -> "TK_PERIOD"
  | TK_PIPE -> "TK_PIPE"
  | TK_PIPE_EQ -> "TK_PIPE_EQ"
  | TK_PIPEPIPE -> "TK_PIPEPIPE"
  | TK_PLUS -> "TK_PLUS"
  | TK_PLUS_EQ -> "TK_PLUS_EQ"
  | TK_QMARK -> "TK_QMARK"
  | TK_RBRACE -> "TK_RBRACE"
  | TK_RBRACK -> "TK_RBRACK"
  | TK_RSQBRACK -> "TK_RSQBRACK"
  | TK_SEMICOLON -> "TK_SEMICOLON"
  | TK_SLASH -> "TK_SLASH"
  | TK_SLASH_EQ -> "TK_SLASH_EQ"
  | TK_STAR -> "TK_STAR"
  | TK_STAR_EQ -> "TK_STAR_EQ"
  | TK_STRING_LITERAL -> "TK_STRING_LITERAL"
  | TK_TILDE -> "TK_TILDE"
  | TK_TYPEDEF_NAME -> "TK_TYPEDEF_NAME"
  | TK_WCHAR_CONSTANT -> "TK_WCHAR_CONSTANT"
  | TK_WSTRING_LITERAL -> "TK_WSTRING_LITERAL"
;;
